# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0966f5a1314a42f2bbbaeec641ce7ab8cd7c4257028289456101f6033e9118a8d115eefc7935cea0d060e98ee0f8a9abfb52fd4ef894565790c635df807a174

test:
  secret_key_base: 08e092f06c14f30dcfcb513dc2af9717ad0abd0d731808ab617208574232586363b1f23c2dca76cd9cb75098b496fc4c109fe59b94d742347f9712caa175d761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
